### ISSUE TITLE
Flutter CanvasKit Crash - RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by wpickachu** [KiraCore/kira-frontend#2]
**The issue happens specifically after this commit (7e9160ca4daab08d8bdb515c9b2f00e6f2091a20) in kira frontend.**

**After some time, the app crashes throwing this error.**

> ![image](https://user-images.githubusercontent.com/50459820/96156500-24a1a000-0edf-11eb-8c6d-e1a020bb08f0.png)

**There's a discussion room similar to this which seems like flutter's issue which you can find here : **[https://github.com/flutter/flutter/issues/67949](https://github.com/flutter/flutter/issues/67949)

**This can also be related to SKIA module which we use for specifically generating avatar for user account.**

**Another problem also looks like below**

> ![image](https://user-images.githubusercontent.com/50459820/96156883-9843ad00-0edf-11eb-92bb-012acf8e9bbe.png)

**Comment by AmanuelYosief** [comment]
Packages that required the use of the web renders SKIA has been removed, this and SKIA related issues have been fixed.

**Comment by wpickachu** [comment]
resolved
